# Spring Boot configuration
spring:
  jmx:
    enabled: false
  jta: 
    enabled: false
  profiles:
    active: dev
  application:
    name: user-svcs
  jersey.application-path: /api   # Jersey dispatcher servlet, make /api as URI root  
  mvc:
    servlet:
      path: /       
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:8082}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

server:
  port: ${appPort:8081}
  
    
management:
  health:
    defaults:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown: 
      enabled: true

logging:
  level:
    org:
      hibernate:
        stat: ERROR
        type: ERROR

info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    versio: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    groupId: '@project.groupId@'
    artifactId: '@project.artifactId@'
    version: '@project.version@'   
 